import type { GeneratedReport, ReportContext } from "../types.js";
import { GeneratedReportSchema } from "../types.js";

// Milestone 8: a deterministic, rule-based report generator — not yet
// LLM-backed, same reasoning as every other agent in this service. Every
// report is built entirely from real fields the backend assembled from
// the ledger + AuditLog — no placeholder content — with graceful
// fallbacks matching documentation/agent.ts's style.

function formatNGN(amount: number): string {
  return new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amount);
}

function num(record: unknown, key: string): number {
  return Number((record as Record<string, unknown>)[key] ?? 0);
}

function str(record: unknown, key: string): string {
  const v = (record as Record<string, unknown>)[key];
  return typeof v === "string" && v.length > 0 ? v : "—";
}

function sumAmountNGN(records: unknown[]): number {
  return records.reduce<number>((sum, r) => sum + num(r, "amountNGN"), 0);
}

function managementReport(c: ReportContext): GeneratedReport {
  const totalDistributedNGN = sumAmountNGN(c.distributions);
  const sourceFacts = ["productName", "symbol", "structureType", "targetSizeNGN", "totalSupply", "approvalReference", "holdings", "distributions"];
  const markdown = `# Management Report — ${c.productName ?? "Untitled Product"}

| Metric | Value |
|---|---|
| Symbol | ${c.symbol ?? "TBD"} |
| Structure type | ${c.structureType ?? "TBD"} |
| Target size | ${c.targetSizeNGN != null ? formatNGN(c.targetSizeNGN) : "TBD"} |
| Total supply (units) | ${c.totalSupply != null ? c.totalSupply.toLocaleString() : "TBD"} |
| SEC approval reference | ${c.approvalReference ?? "Not yet approved"} |
| Investor holdings recorded | ${c.holdings.length} |
| Distributions paid | ${c.distributions.length} (${formatNGN(totalDistributedNGN)} total) |

_Generated by the AI Reporting Agent for the Issuing House. Advisory only — a management view of this deal's lifecycle to date._`;
  return { reportType: "management", title: `Management Report — ${c.productName ?? "Untitled Product"}`, markdown, sourceFacts };
}

function investorReport(c: ReportContext): GeneratedReport {
  const sourceFacts = ["generatedFor", "holdings", "distributions"];
  const holdingsRows =
    c.holdings.length > 0
      ? c.holdings.map((h) => `| ${str(h, "productName")} | ${str(h, "symbol")} | ${num(h, "units").toLocaleString()} | ${formatNGN(num(h, "amountNGN"))} |`).join("\n")
      : "| _No holdings yet_ | | | |";
  const distributionsRows =
    c.distributions.length > 0
      ? c.distributions.map((d) => `| ${str(d, "productName")} | ${str(d, "periodLabel")} | ${formatNGN(num(d, "amountNGN"))} |`).join("\n")
      : "| _No distributions yet_ | | |";
  const totalDistributedNGN = sumAmountNGN(c.distributions);
  const markdown = `# Investor Report — ${c.generatedFor ?? "Investor"}

## Holdings
| Product | Symbol | Units | Amount |
|---|---|---|---|
${holdingsRows}

## Distributions received
| Product | Period | Amount |
|---|---|---|
${distributionsRows}

**Total distributed to date:** ${formatNGN(totalDistributedNGN)}

_Generated by the AI Reporting Agent, from your own holdings and distribution records only. Advisory only._`;
  return { reportType: "investor", title: `Investor Report — ${c.generatedFor ?? "Investor"}`, markdown, sourceFacts };
}

function complianceReport(c: ReportContext): GeneratedReport {
  const comp = c.compliance;
  const sourceFacts = ["productName", "compliance"];
  const gapsSection = (label: string, gaps: string[] | undefined) =>
    `### ${label}\n${gaps && gaps.length > 0 ? gaps.map((g) => `- ${g}`).join("\n") : "_None._"}`;
  const markdown = `# Compliance Report — ${c.productName ?? "Untitled Product"}

**Ready for SEC submission:** ${comp?.readyForSubmission ? "Yes" : "No"}

${gapsSection("Workflow gaps", comp?.workflowGaps)}

${gapsSection("Shariah checklist gaps", comp?.shariahChecklistGaps)}

${gapsSection("Documents required for filing", comp?.missingDocuments)}

_Generated by the AI Reporting Agent from the Compliance Agent's assessment. Advisory only — reflects state at generation time._`;
  return { reportType: "compliance", title: `Compliance Report — ${c.productName ?? "Untitled Product"}`, markdown, sourceFacts };
}

function regulatoryReport(c: ReportContext): GeneratedReport {
  const sourceFacts = ["productName", "symbol", "targetSizeNGN", "totalSupply", "approvalReference", "certificationNotes", "approvalNotes", "distributions"];
  const totalDistributedNGN = sumAmountNGN(c.distributions);
  const markdown = `# Regulatory Report — ${c.productName ?? "Untitled Product"}

**SEC approval reference:** ${c.approvalReference ?? "Not yet approved"}
**Target size:** ${c.targetSizeNGN != null ? formatNGN(c.targetSizeNGN) : "TBD"}
**Total supply:** ${c.totalSupply != null ? c.totalSupply.toLocaleString() : "TBD"} units

## Shariah certification
${c.certificationNotes ?? "_Not yet certified._"}

## Trustee approval
${c.approvalNotes ?? "_Not yet approved._"}

## Distributions to date
${c.distributions.length} distribution(s) recorded, totaling ${formatNGN(totalDistributedNGN)}.

_Generated by the AI Reporting Agent for regulatory oversight. Advisory only._`;
  return { reportType: "regulatory", title: `Regulatory Report — ${c.productName ?? "Untitled Product"}`, markdown, sourceFacts };
}

function portfolioReport(c: ReportContext): GeneratedReport {
  const sourceFacts = ["generatedFor", "investorProfiles", "holdings"];
  const verified = c.investorProfiles.filter((p) => str(p, "kycStatus") === "KycVerified").length;
  const pending = c.investorProfiles.filter((p) => str(p, "kycStatus") === "KycPending").length;
  const rejected = c.investorProfiles.filter((p) => str(p, "kycStatus") === "KycRejected").length;
  const totalAllocatedNGN = sumAmountNGN(c.holdings);
  const investorRows =
    c.investorProfiles.length > 0
      ? c.investorProfiles.map((p) => `| ${str(p, "fullName")} | ${str(p, "email")} | ${str(p, "kycStatus")} |`).join("\n")
      : "| _No investors onboarded yet_ | | |";
  const markdown = `# Distributor Portfolio Report — ${c.generatedFor ?? "Distributor"}

| Metric | Value |
|---|---|
| Investors onboarded | ${c.investorProfiles.length} |
| KYC verified | ${verified} |
| KYC pending | ${pending} |
| KYC rejected | ${rejected} |
| Units allocated (subscriptions) | ${c.holdings.length} |
| Total allocated | ${formatNGN(totalAllocatedNGN)} |

## Investors
| Name | Email | KYC status |
|---|---|---|
${investorRows}

_Generated by the AI Reporting Agent from your own investor book. Advisory only._`;
  return { reportType: "portfolio", title: `Distributor Portfolio Report — ${c.generatedFor ?? "Distributor"}`, markdown, sourceFacts };
}

function custodyReport(c: ReportContext): GeneratedReport {
  const sourceFacts = ["generatedFor", "investmentNotes", "distributionRequests", "distributions"];
  const totalDistributedNGN = sumAmountNGN(c.distributions);
  const pendingRequests = c.distributionRequests.length;
  const noteRows =
    c.investmentNotes.length > 0
      ? c.investmentNotes.map((n) => `| ${str(n, "productName")} | ${str(n, "symbol")} | ${num(n, "totalSupply").toLocaleString()} |`).join("\n")
      : "| _No notes under custody yet_ | | |";
  const markdown = `# Custodian Report — ${c.generatedFor ?? "Custodian"}

| Metric | Value |
|---|---|
| Notes under custody | ${c.investmentNotes.length} |
| Distribution requests pending Trustee approval | ${pendingRequests} |
| Distributions paid | ${c.distributions.length} (${formatNGN(totalDistributedNGN)} total) |

## Notes under custody
| Product | Symbol | Total supply |
|---|---|---|
${noteRows}

_Generated by the AI Reporting Agent from your own custody records. Advisory only._`;
  return { reportType: "custody", title: `Custodian Report — ${c.generatedFor ?? "Custodian"}`, markdown, sourceFacts };
}

function shariahReport(c: ReportContext): GeneratedReport {
  const sourceFacts = ["generatedFor", "shariahReviews"];
  const certified = c.shariahReviews.filter((r) => str(r, "status") === "Certified");
  const pending = c.shariahReviews.filter((r) => str(r, "status") === "Pending");
  const certifiedRows =
    certified.length > 0
      ? certified.map((r) => `| ${str(r, "productName")} | ${str(r, "structureType")} | ${str(r, "certificationNotes")} |`).join("\n")
      : "| _None certified yet_ | | |";
  const markdown = `# Shariah Advisor Report — ${c.generatedFor ?? "Shariah Advisor"}

| Metric | Value |
|---|---|
| Structures reviewed | ${c.shariahReviews.length} |
| Certified compliant | ${certified.length} |
| Pending certification | ${pending.length} |

## Certified structures
| Product | Structure type | Certification notes |
|---|---|---|
${certifiedRows}

_Generated by the AI Reporting Agent from your own certification history. Advisory only._`;
  return { reportType: "shariah", title: `Shariah Advisor Report — ${c.generatedFor ?? "Shariah Advisor"}`, markdown, sourceFacts };
}

function platformReport(c: ReportContext): GeneratedReport {
  const sourceFacts = ["organizations", "users"];
  const activeOrgs = c.organizations.filter((o) => (o as Record<string, unknown>).active === true).length;
  const roleCounts = new Map<string, number>();
  for (const o of c.organizations) {
    const role = str(o, "role");
    roleCounts.set(role, (roleCounts.get(role) ?? 0) + 1);
  }
  const roleRows =
    roleCounts.size > 0
      ? [...roleCounts.entries()].map(([role, n]) => `| ${role} | ${n} |`).join("\n")
      : "| _No organizations onboarded yet_ | |";
  const markdown = `# Platform Report — AmanaX Network

| Metric | Value |
|---|---|
| Organizations onboarded | ${c.organizations.length} |
| Active organizations | ${activeOrgs} |
| Users onboarded | ${c.users.length} |

## Organizations by role
| Role | Count |
|---|---|
${roleRows}

_Generated by the AI Reporting Agent from the network's own Organization/User records. Advisory only — a snapshot at generation time._`;
  return { reportType: "platform", title: "Platform Report — AmanaX Network", markdown, sourceFacts };
}

export async function runReportingAgent(context: ReportContext): Promise<GeneratedReport> {
  const report =
    context.reportType === "management"
      ? managementReport(context)
      : context.reportType === "investor"
        ? investorReport(context)
        : context.reportType === "compliance"
          ? complianceReport(context)
          : context.reportType === "regulatory"
            ? regulatoryReport(context)
            : context.reportType === "portfolio"
              ? portfolioReport(context)
              : context.reportType === "custody"
                ? custodyReport(context)
                : context.reportType === "shariah"
                  ? shariahReport(context)
                  : platformReport(context);
  return GeneratedReportSchema.parse(report);
}
