import type { DealContext, GeneratedDocument } from "../types.js";
import { GeneratedDocumentSchema } from "../types.js";

// Milestone 4: a deterministic, rule-based document generator — not yet
// LLM-backed, same reasoning as productStructuring/agent.ts and
// compliance/agent.ts. Reads the same Trustee-review-stage DealContext
// shape the Compliance Agent uses (see api/regulatory.ts in the backend):
// `structure` carries the deal terms, `shariahReview`/`trusteeReview`
// carry each stage's own notes. Every document is built entirely from
// those real fields — no lorem-ipsum placeholders — and `sourceFacts`
// records exactly which fields were used, for traceability.

type StructureFields = {
  productName?: string;
  description?: string;
  structureType?: string;
  targetSizeNGN?: number;
  tenorMonths?: number;
  profitMechanism?: string;
  minSubscriptionNGN?: number;
  redemptionTerms?: string;
};

type ShariahFields = { certificationNotes?: string };
type TrusteeFields = { approvalNotes?: string };

function formatNGN(amount: number): string {
  return new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(amount);
}

function termSheet(s: StructureFields): GeneratedDocument {
  const sourceFacts = [
    "productName",
    "structureType",
    "targetSizeNGN",
    "tenorMonths",
    "profitMechanism",
    "minSubscriptionNGN",
    "redemptionTerms",
  ];
  const markdown = `# Term Sheet — ${s.productName ?? "Untitled Product"}

| Term | Value |
|---|---|
| Structure type | ${s.structureType ?? "TBD"} |
| Target issuance size | ${s.targetSizeNGN != null ? formatNGN(s.targetSizeNGN) : "TBD"} |
| Tenor | ${s.tenorMonths != null ? `${s.tenorMonths} months` : "TBD"} |
| Profit mechanism | ${s.profitMechanism ?? "TBD"} |
| Minimum subscription | ${s.minSubscriptionNGN != null ? formatNGN(s.minSubscriptionNGN) : "TBD"} |
| Redemption terms | ${s.redemptionTerms ?? "TBD"} |

_Generated by the AI Documentation Agent from the finalized product structure. Advisory only — review before filing._`;
  return { kind: "TermSheet", title: `Term Sheet — ${s.productName ?? "Untitled Product"}`, markdown, sourceFacts };
}

function investmentSummary(s: StructureFields): GeneratedDocument {
  const sourceFacts = ["productName", "description", "structureType", "targetSizeNGN", "tenorMonths"];
  const markdown = `# Investment Summary — ${s.productName ?? "Untitled Product"}

${s.description ?? "No description on file."}

This ${s.structureType ?? "Shariah-compliant"} investment note targets an issuance size of ${
    s.targetSizeNGN != null ? formatNGN(s.targetSizeNGN) : "an amount to be determined"
  } over a tenor of ${s.tenorMonths != null ? `${s.tenorMonths} months` : "a period to be determined"}. Profit is distributed via: ${
    s.profitMechanism ?? "a mechanism to be determined"
  }.

_Generated by the AI Documentation Agent. Advisory only — review before filing._`;
  return { kind: "InvestmentSummary", title: `Investment Summary — ${s.productName ?? "Untitled Product"}`, markdown, sourceFacts };
}

function approvalPack(s: StructureFields, shariah: ShariahFields | null, trustee: TrusteeFields | null): GeneratedDocument {
  const sourceFacts = ["productName", "certificationNotes", "approvalNotes"];
  const markdown = `# Approval Pack — ${s.productName ?? "Untitled Product"}

## Shariah certification
${shariah?.certificationNotes ? shariah.certificationNotes : "_Not yet certified._"}

## Trustee approval
${trustee?.approvalNotes ? trustee.approvalNotes : "_Not yet approved._"}

_Generated by the AI Documentation Agent, bundling the Shariah Advisor's certification and the Trustee's approval for SEC review. Advisory only._`;
  return { kind: "ApprovalPack", title: `Approval Pack — ${s.productName ?? "Untitled Product"}`, markdown, sourceFacts };
}

function regulatoryFiling(s: StructureFields): GeneratedDocument {
  const sourceFacts = ["productName", "structureType", "targetSizeNGN", "tenorMonths", "redemptionTerms"];
  const markdown = `# Regulatory Filing — ${s.productName ?? "Untitled Product"}

**To:** Securities and Exchange Commission (Nigeria)
**Re:** Application for approval of issuance — ${s.productName ?? "Untitled Product"}

The Issuing House submits this ${s.structureType ?? "Shariah-compliant"} investment note, target size ${
    s.targetSizeNGN != null ? formatNGN(s.targetSizeNGN) : "TBD"
  }, tenor ${s.tenorMonths != null ? `${s.tenorMonths} months` : "TBD"}, for regulatory approval. Redemption: ${
    s.redemptionTerms ?? "TBD"
  }. This filing has completed Shariah certification and Trustee review per the accompanying Approval Pack.

_Generated by the AI Documentation Agent. Advisory only — a human at the Issuing House must review and approve before this is filed with the SEC._`;
  return { kind: "RegulatoryFiling", title: `Regulatory Filing — ${s.productName ?? "Untitled Product"}`, markdown, sourceFacts };
}

export async function runDocumentationAgent(context: DealContext): Promise<GeneratedDocument[]> {
  const structure = (context.structure ?? {}) as StructureFields;
  const shariahReview = context.shariahReview as ShariahFields | null;
  const trusteeReview = context.trusteeReview as TrusteeFields | null;

  const documents = [
    termSheet(structure),
    investmentSummary(structure),
    approvalPack(structure, shariahReview, trusteeReview),
    regulatoryFiling(structure),
  ];
  return documents.map((doc) => GeneratedDocumentSchema.parse(doc));
}
